services:
  app:
    build: .
    container_name: payslip_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./volumes/tmp:/app/tmp
      - ./volumes/logs:/app/logs
    expose:
      - "5000"

  nginx:
    image: nginx:1.25-alpine
    container_name: payslip_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - app

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./nginx/certbot/conf:/etc/letsencrypt
  #     - ./nginx/certbot/www:/var/www/certbot
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d yourdomain.com

